### PR TITLE
correct library name on first and last line

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by thomblake** [comment]
should modify lib/js3-foot.el and lib/js3-head.el

**Comment by tarsius** [comment]
This is confusing. Do you generate `js3-mode.el` from the files in `lib`?

**Comment by thomblake** [comment]
Yes. Update the files in `lib` and then run `bin/build` - the `.el` file is also committed to the repo just for legacy reasons.

**Comment by tarsius** [comment]
Okay, I have done that.

I have also fixed some other issues the byte-compiler told me about. (Addressing these issues was harder than doing so should have been because the byte-compiler told me about errors in `js3-mode.el` but I then had to determine the location inside one of the files in `lib/` to actually fix it. Therefore I would strongly suggest you stop concatenating the "input libraries" to generate `js3-mode.el` -- "legacy reasons" doesn't seem like a good enough reason to make maintenance harder in the present and future.)

**Comment by thomblake** [comment]
:+1:

**Comment by tarsius** [comment]
Thanks for commit access, but I am interested. I only came here to fix this issue because I noticed it as part of my work on the [Emacsmirror](https://emacsmirror.net). Please revoke it again.

**Comment by tarsius** [comment]
I still have commit access and have merged this now. Please remove my commit access - I don't want to do anymore but this.

**Pull request merged**
